### ISSUE TITLE
你好 我想知道你怎么支付 Chrome 网上应用店开发者注册费 的

### ISSUE THREAD

**Issue by riskers** [Sneezry/chrome_extensions_and_apps_programming#5]
就是这个界面：
![p](http://gyb-demo.qiniudn.com/15-7-23/46228157.jpg)
大陆并不能支付。
支付宝也没有境外付

**Comment by Sneezry** [comment]
有人说用招商银行支持visa的卡片地址选择香港是可以注册的，我的账号当初是谷奥的编辑帮我注册的

**Comment by rustjson** [comment]
@riskers 我的招商银行信用卡全币种的就可以。。。。。。

**Comment by riskers** [comment]
@Red-wolf-s-husband 我重新申请了一张信用卡 就可以了，以前只支持银联的。还有，你怎么会在这里

**Comment by rustjson** [comment]
我为毛不能再这里？

**Comment by FrankHan** [comment]
有一张双币种的信用卡，然后付了大概8美元吧。

**Comment by greatghoul** [comment]
没有收费时就注册了。。

**Comment by kuangchanglang** [comment]
同支付不了，有人帮我发布一个小插件么

**Comment by MuYunyun** [comment]
某宝上靠谱么
