### ISSUE TITLE
一个同步/异步问题讨论

### ISSUE THREAD

**Issue by WuHuaJi0** [Sneezry/chrome_extensions_and_apps_programming#6]
### 一个同步/异步问题讨论
这个问题本质上是js同步异步的问题，和这个仓库教程没有太大关系，但是问题困扰我很久了，所以斗胆发个issue，大家讨论下。

问题还原：我这里想做的事情是
1，拦截http请求，然后对请求头进行修改一些修改，也就是用 ：`chrome.webRequest.onBeforeSendHeaders.addListener`这个函数。

2，这函数里面接受一个参数，对传入的请求对象某些操作，大概也就是这样：
```
chrome.webRequest.onBeforeSendHeaders.addListener(
    function(details){
       //do something 
       return {requestHeaders: details.requestHeaders};
    },
    {
        urls: [
            "<all_urls>"
        ]
    },
    [
        "blocking",
        "requestHeaders"
    ]
);
```

3，这里，具体怎么修改details对象，我需要根据用户的设置进行操作；而且这里，我想将用户的设置存在`chrome.storage.sync` 方便设置能进行同步。但是 `chrome.storage.sync.get`是个异步函数，通过get拿到存储信息之后，并不能返回出来，而要传入一个回调函数。

这时候就成了这样：
```
function(details){
    chrome.storage.sync.get('user_settings',function (result) {
        //根据拿到的用户设置，来操作details
    })
    return {requestHeaders: details.requestHeaders}
}
```

但是我们知道，这样由于异步的关系，这样`details`并没有被修改，就直接返回了，所以说`从sync中读取数据并进行相关操作，并没有生效`。

这里，我尝试了Promise、async/await等各种办法，都没能解决这里异步函数拿到返回值再进行相关操作的问题。

不知道这里有什么解决办法，还是说由于js本身的异步机制没办法解决？

**Comment by Sneezry** [comment]
这里有类似的问题 https://stackoverflow.com/questions/29152166/asynchronous-operation-in-blocking-chrome-webrequest-onbeforesendheaders-listene

我同意这个问题里的回答，即在本地做缓存。你可以在扩展加载完成后就将 chrome.storage.sync 中的数据放到本地做缓存，比如放在 localStorage，或者如果有常驻的 background 就直接放在内存，数据有变化的时候再同步到 chrome.storage.sync。

**Comment by WuHuaJi0** [comment]
确实这样是个迂回的解决办法，多谢 ：）
