### ISSUE TITLE
关于http_server应用代码中background.js代码的一个疑问

### ISSUE THREAD

**Issue by 209914097** [Sneezry/chrome_extensions_and_apps_programming#9]
您好！我在浏览器运行了一下http_server这个应用，其中background.js中有一段代码(52-54行)：

`var body = "<h1>It Works!</h1>"+`
               `"<hr />"+`
               `"Request Header:<br />"+header;`
</br>
在浏览器显示是:
<h1>It Works!</h1>

当我想把"It Works"变为中文字符的时候会出现乱码，请问是什么原因呢？
另外您在书中提到"http协议中，一个字符占8位，故仅需1个字节就可完成存储"，那么我想问下如果遇到中文字符，一个汉字占2个字节，http协议1个字节如何完成存储呢？

**Comment by Sneezry** [comment]
1个字节最多只能存储256以下的数字，所以一个字节是无法储存一个汉字的。

1个汉字通常使用两个以上的字节进行存储，所以在将字符串转换为buffer的时候，相应的一个汉字需要多个buffer进行存储。

书中的例子我们使用`str2ab`来做字符串到buffer的转换，这里有一个偷懒的地方导致它只能处理char code在256以下的字符，那就是

```
bufView[i] = str.charCodeAt(i);
```

这里默认了`str.charCodeAt(i)`一定小于256，但实际上汉字是大于这个数字的。

如果要支持中文，这里有两个地方需要改：

1、buffer长度不能用`str.length`决定，因为对于包含中文的字符串，一个汉字的length也是1，这里我们需要获取的是byte length，具体实现可以参见<https://stackoverflow.com/questions/5515869/string-length-in-bytes-in-javascript>。

2、转换的时候不能单纯使用`bufView[i] = str.charCodeAt(i)`，需要将大于256的字符拆分成多个8位字符进行存储。

**Comment by 209914097** [comment]
谢谢您那么热心详细的回答
